set NOP       0
set UNLOCK  1
set LOCK   2
set OPEN        3

set ACTION_TYPE_INACTIVE 0
set ACTION_TYPE_JUMP 1

set PROFILE_1(LONG_COND_VALUE_HI) 150
set PROFILE_1(LONG_COND_VALUE_LO) 50
set PROFILE_1(LONG_CT_OFF) 0
set PROFILE_1(LONG_CT_ON) 0
set PROFILE_1(LONG_JT_OFF)      $OPEN
set PROFILE_1(LONG_JT_ON)       $OPEN
set PROFILE_1(LONG_PERMISSION_MASK)       0
set PROFILE_1(LONG_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_1(SHORT_COND_VALUE_HI) 150
set PROFILE_1(SHORT_COND_VALUE_LO) 50
set PROFILE_1(SHORT_CT_OFF) 0
set PROFILE_1(SHORT_CT_ON) 0
set PROFILE_1(SHORT_JT_OFF)      $UNLOCK
set PROFILE_1(SHORT_JT_ON)       $LOCK
set PROFILE_1(SHORT_PERMISSION_MASK)       0
set PROFILE_1(SHORT_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_1(UI_DESCRIPTION) ""
set PROFILE_1(UI_HINT)  1
set PROFILE_1(UI_TEMPLATE)    $PROFILE_1(UI_DESCRIPTION)


set PROFILE_2(LONG_COND_VALUE_HI) 150
set PROFILE_2(LONG_COND_VALUE_LO) 50
set PROFILE_2(LONG_CT_OFF) 0
set PROFILE_2(LONG_CT_ON) 0
set PROFILE_2(LONG_JT_OFF)      $UNLOCK
set PROFILE_2(LONG_JT_ON)       $LOCK
set PROFILE_2(LONG_PERMISSION_MASK)       0
set PROFILE_2(LONG_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_2(SHORT_COND_VALUE_HI) 150
set PROFILE_2(SHORT_COND_VALUE_LO) 50
set PROFILE_2(SHORT_CT_OFF) 0
set PROFILE_2(SHORT_CT_ON) 0
set PROFILE_2(SHORT_JT_OFF)      $UNLOCK
set PROFILE_2(SHORT_JT_ON)       $LOCK
set PROFILE_2(SHORT_PERMISSION_MASK)       0
set PROFILE_2(SHORT_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_2(UI_DESCRIPTION) ""
set PROFILE_2(UI_HINT)  2
set PROFILE_2(UI_TEMPLATE)    $PROFILE_2(UI_DESCRIPTION)


set PROFILE_3(LONG_COND_VALUE_HI) 150
set PROFILE_3(LONG_COND_VALUE_LO) 50
set PROFILE_3(LONG_CT_OFF) 0
set PROFILE_3(LONG_CT_ON) 0
set PROFILE_3(LONG_JT_OFF)      $OPEN
set PROFILE_3(LONG_JT_ON)       $OPEN
set PROFILE_3(LONG_PERMISSION_MASK)       0
set PROFILE_3(LONG_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_3(SHORT_COND_VALUE_HI) 150
set PROFILE_3(SHORT_COND_VALUE_LO) 50
set PROFILE_3(SHORT_CT_OFF) 0
set PROFILE_3(SHORT_CT_ON) 0
set PROFILE_3(SHORT_JT_OFF)      $OPEN
set PROFILE_3(SHORT_JT_ON)       $OPEN
set PROFILE_3(SHORT_PERMISSION_MASK)       0
set PROFILE_3(SHORT_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_3(UI_DESCRIPTION) ""
set PROFILE_3(UI_HINT)  3
set PROFILE_3(UI_TEMPLATE)    $PROFILE_3(UI_DESCRIPTION)


set PROFILE_4(LONG_COND_VALUE_HI) 150
set PROFILE_4(LONG_COND_VALUE_LO) 50
set PROFILE_4(LONG_CT_OFF) 0
set PROFILE_4(LONG_CT_ON) 0
set PROFILE_4(LONG_JT_OFF)      $UNLOCK
set PROFILE_4(LONG_JT_ON)       $UNLOCK
set PROFILE_4(LONG_PERMISSION_MASK)       0
set PROFILE_4(LONG_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_4(SHORT_COND_VALUE_HI) 150
set PROFILE_4(SHORT_COND_VALUE_LO) 50
set PROFILE_4(SHORT_CT_OFF) 0
set PROFILE_4(SHORT_CT_ON) 0
set PROFILE_4(SHORT_JT_OFF)      $UNLOCK
set PROFILE_4(SHORT_JT_ON)       $UNLOCK
set PROFILE_4(SHORT_PERMISSION_MASK)       0
set PROFILE_4(SHORT_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_4(UI_DESCRIPTION) ""
set PROFILE_4(UI_HINT)  4
set PROFILE_4(UI_TEMPLATE)    $PROFILE_4(UI_DESCRIPTION)


set PROFILE_5(LONG_COND_VALUE_HI) 150
set PROFILE_5(LONG_COND_VALUE_LO) 50
set PROFILE_5(LONG_CT_OFF) 0
set PROFILE_5(LONG_CT_ON) 0
set PROFILE_5(LONG_JT_OFF)      $LOCK
set PROFILE_5(LONG_JT_ON)       $LOCK
set PROFILE_5(LONG_PERMISSION_MASK)       0
set PROFILE_5(LONG_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_5(SHORT_COND_VALUE_HI) 150
set PROFILE_5(SHORT_COND_VALUE_LO) 50
set PROFILE_5(SHORT_CT_OFF) 0
set PROFILE_5(SHORT_CT_ON) 0
set PROFILE_5(SHORT_JT_OFF)      $LOCK
set PROFILE_5(SHORT_JT_ON)       $LOCK
set PROFILE_5(SHORT_PERMISSION_MASK)       0
set PROFILE_5(SHORT_PROFILE_ACTION_TYPE)       $ACTION_TYPE_JUMP

set PROFILE_5(UI_DESCRIPTION) ""
set PROFILE_5(UI_HINT)  5
set PROFILE_5(UI_TEMPLATE)    $PROFILE_5(UI_DESCRIPTION)


set PROFILE_6(LONG_PROFILE_ACTION_TYPE)  $ACTION_TYPE_INACTIVE
set PROFILE_6(SHORT_PROFILE_ACTION_TYPE) $ACTION_TYPE_INACTIVE
set PROFILE_6(UI_DESCRIPTION)  "Die Taste ist nicht aktiv."
set PROFILE_6(UI_TEMPLATE) $PROFILE_6(UI_DESCRIPTION)
set PROFILE_6(UI_HINT) 6