set NOP       0
set ON_DELAY  1
set RAMP_ON   2
set ON        3
set OFF_DELAY 4
set RAMP_OFF  5
set OFF       6

set NOT_ACTIVE 0
set DRIVE_UP  3
set DRIVE_DOWN  4
set DRIVE_LAST_DIR 5

set PROFILE_1(LONG_COND_VALUE_HI) 150
set PROFILE_1(LONG_COND_VALUE_LO) 50
set PROFILE_1(LONG_CT_OFF) 0
set PROFILE_1(LONG_CT_OFFDELAY) 0
set PROFILE_1(LONG_CT_ON) 0
set PROFILE_1(LONG_CT_ONDELAY) 0
set PROFILE_1(LONG_CT_RAMPOFF) 0
set PROFILE_1(LONG_CT_RAMPON) 0
set PROFILE_1(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_1(LONG_DIM_MAX_HUE) 360
set PROFILE_1(LONG_DIM_MAX_LEVEL) {1.0 range 0.0  - 1.0}
set PROFILE_1(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_1(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_1(LONG_DIM_MIN_HUE) 360
set PROFILE_1(LONG_DIM_MIN_LEVEL) 0.000000
set PROFILE_1(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_1(LONG_DIM_STEP) {0.05 range 0.00 - 1.00}
set PROFILE_1(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_1(LONG_DIM_STEP_HUE) {0 range 0 - 180}
set PROFILE_1(LONG_DIM_STEP_SATURATION) 0
set PROFILE_1(LONG_JT_OFF)      $ON_DELAY
set PROFILE_1(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_1(LONG_JT_ON)       $RAMP_ON
set PROFILE_1(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_1(LONG_JT_RAMPOFF)  $RAMP_ON
set PROFILE_1(LONG_JT_RAMPON)   $ON
set PROFILE_1(LONG_MULTIEXECUTE) 1
set PROFILE_1(LONG_OFFDELAY_BLINK) 0
set PROFILE_1(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_1(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_1(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_1(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_1(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_1(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_1(LONG_OFF_HUE) {361 range 0 - 361}
set PROFILE_1(LONG_OFF_LEVEL) 0.000000
set PROFILE_1(LONG_OFF_SATURATION) {1.01 range 0.0 - 1.010}
set PROFILE_1(LONG_OFF_TIME_BASE) 7
set PROFILE_1(LONG_OFF_TIME_FACTOR) 31
set PROFILE_1(LONG_OFF_TIME_MODE) 0
set PROFILE_1(LONG_ONDELAY_MODE) 0
set PROFILE_1(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_1(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_1(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_1(LONG_ON_HUE) {361 range 0 - 361}
set PROFILE_1(LONG_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_1(LONG_ON_MIN_LEVEL) 0.100000
set PROFILE_1(LONG_ON_SATURATION) {1.010 range 0.0 - 1.010}
set PROFILE_1(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_1(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_1(LONG_ON_TIME_MODE) 0
set PROFILE_1(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_1(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_UP $NOT_ACTIVE}]
set PROFILE_1(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_1(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_1(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_1(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_1(LONG_RAMP_START_STEP) {0.05 range 0.00 - 1.00}
set PROFILE_1(SHORT_COND_VALUE_HI) 150
set PROFILE_1(SHORT_COND_VALUE_LO) 50
set PROFILE_1(SHORT_CT_OFF) 0
set PROFILE_1(SHORT_CT_OFFDELAY) 0
set PROFILE_1(SHORT_CT_ON) 0
set PROFILE_1(SHORT_CT_ONDELAY) 0
set PROFILE_1(SHORT_CT_RAMPOFF) 0
set PROFILE_1(SHORT_CT_RAMPON) 0
set PROFILE_1(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_1(SHORT_DIM_MAX_HUE) 360
set PROFILE_1(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_1(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_1(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_1(SHORT_DIM_MIN_HUE) 360
set PROFILE_1(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_1(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_1(SHORT_DIM_STEP) 0.050000
set PROFILE_1(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_1(SHORT_DIM_STEP_HUE) 0
set PROFILE_1(SHORT_DIM_STEP_SATURATION) 0
set PROFILE_1(SHORT_JT_OFF)      $ON_DELAY
set PROFILE_1(SHORT_JT_OFFDELAY) $ON
set PROFILE_1(SHORT_JT_ON)       [subst {$ON_DELAY $RAMP_ON}]
set PROFILE_1(SHORT_JT_ONDELAY)  $ON_DELAY
set PROFILE_1(SHORT_JT_RAMPOFF)  $RAMP_ON
set PROFILE_1(SHORT_JT_RAMPON)   $RAMP_ON
set PROFILE_1(SHORT_MULTIEXECUTE) 0
set PROFILE_1(SHORT_OFFDELAY_BLINK) {0 1}
set PROFILE_1(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_1(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_1(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_1(SHORT_OFFDELAY_TIME_BASE) 0
set PROFILE_1(SHORT_OFFDELAY_TIME_FACTOR) 0
set PROFILE_1(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_1(SHORT_OFF_HUE) {361 range 0 - 361}
set PROFILE_1(SHORT_OFF_LEVEL) 0.000000
set PROFILE_1(SHORT_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_1(SHORT_OFF_TIME_BASE) 7
set PROFILE_1(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_1(SHORT_OFF_TIME_MODE) 0
set PROFILE_1(SHORT_ONDELAY_MODE) 0
set PROFILE_1(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_1(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_1(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_1(SHORT_ON_HUE) {361 range 0 - 361}
set PROFILE_1(SHORT_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_1(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_1(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_1(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_1(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_1(SHORT_ON_TIME_MODE) 0
set PROFILE_1(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_1(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_1(SHORT_RAMPOFF_TIME_BASE) 0
set PROFILE_1(SHORT_RAMPOFF_TIME_FACTOR) 5
set PROFILE_1(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_1(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_1(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_1(UI_DESCRIPTION) ""
set PROFILE_1(UI_HINT)  1
set PROFILE_1(UI_TEMPLATE)    $PROFILE_1(UI_DESCRIPTION)

set PROFILE_2(LONG_COND_VALUE_HI) 150
set PROFILE_2(LONG_COND_VALUE_LO) 50
set PROFILE_2(LONG_CT_OFF) 0
set PROFILE_2(LONG_CT_OFFDELAY) 0
set PROFILE_2(LONG_CT_ON) 0
set PROFILE_2(LONG_CT_ONDELAY) 0
set PROFILE_2(LONG_CT_RAMPOFF) 0
set PROFILE_2(LONG_CT_RAMPON) 0
set PROFILE_2(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_2(LONG_DIM_MAX_HUE) 360
set PROFILE_2(LONG_DIM_MAX_LEVEL) 1.000000
set PROFILE_2(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_2(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_2(LONG_DIM_MIN_HUE) 360
set PROFILE_2(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_2(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_2(LONG_DIM_STEP) {0.05 range 0.00 - 1.00}
set PROFILE_2(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_2(LONG_DIM_STEP_HUE) {0 range 0 - 180}
set PROFILE_2(LONG_DIM_STEP_SATURATION) 0
set PROFILE_2(LONG_JT_OFF)      $OFF
set PROFILE_2(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_2(LONG_JT_ON)       $RAMP_OFF
set PROFILE_2(LONG_JT_ONDELAY)  $OFF
set PROFILE_2(LONG_JT_RAMPOFF)  $OFF
set PROFILE_2(LONG_JT_RAMPON)   $OFF_DELAY
set PROFILE_2(LONG_MULTIEXECUTE) 1
set PROFILE_2(LONG_OFFDELAY_BLINK) {1 0}
set PROFILE_2(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_2(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_2(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_2(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_2(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_2(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_2(LONG_OFF_HUE) {361 range 0 - 361}
set PROFILE_2(LONG_OFF_LEVEL) 0.000000
set PROFILE_2(LONG_OFF_SATURATION) 1.01
set PROFILE_2(LONG_OFF_TIME_BASE) 7
set PROFILE_2(LONG_OFF_TIME_FACTOR) 31
set PROFILE_2(LONG_OFF_TIME_MODE) 0
set PROFILE_2(LONG_ONDELAY_MODE) 0
set PROFILE_2(LONG_ONDELAY_TIME_BASE) 0
set PROFILE_2(LONG_ONDELAY_TIME_FACTOR) 0
set PROFILE_2(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_2(LONG_ON_HUE) {361 range 0 - 361}
set PROFILE_2(LONG_ON_LEVEL) 0.0
set PROFILE_2(LONG_ON_MIN_LEVEL) 0.100000
set PROFILE_2(LONG_ON_SATURATION) 1.01
set PROFILE_2(LONG_ON_TIME_BASE) 7
set PROFILE_2(LONG_ON_TIME_FACTOR) 31
set PROFILE_2(LONG_ON_TIME_MODE) 0
set PROFILE_2(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_2(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_DOWN $NOT_ACTIVE}]
set PROFILE_2(LONG_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_2(LONG_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_2(LONG_RAMPON_TIME_BASE) 0
set PROFILE_2(LONG_RAMPON_TIME_FACTOR) 5
set PROFILE_2(LONG_RAMP_START_STEP) 0.050000
set PROFILE_2(SHORT_COND_VALUE_HI) 150
set PROFILE_2(SHORT_COND_VALUE_LO) 50
set PROFILE_2(SHORT_CT_OFF) 0
set PROFILE_2(SHORT_CT_OFFDELAY) 0
set PROFILE_2(SHORT_CT_ON) 0
set PROFILE_2(SHORT_CT_ONDELAY) 0
set PROFILE_2(SHORT_CT_RAMPOFF) 0
set PROFILE_2(SHORT_CT_RAMPON) 0
set PROFILE_2(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_2(SHORT_DIM_MAX_HUE) 360
set PROFILE_2(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_2(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_2(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_2(SHORT_DIM_MIN_HUE) 360
set PROFILE_2(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_2(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_2(SHORT_DIM_STEP) 0.050000
set PROFILE_2(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_2(SHORT_DIM_STEP_HUE) 0
set PROFILE_2(SHORT_DIM_STEP_SATURATION) 0
set PROFILE_2(SHORT_JT_OFF)       $OFF
set PROFILE_2(SHORT_JT_OFFDELAY)  $RAMP_OFF
set PROFILE_2(SHORT_JT_ON)        [subst {$ON_DELAY $OFF_DELAY}]
set PROFILE_2(SHORT_JT_ONDELAY)   $OFF
set PROFILE_2(SHORT_JT_RAMPOFF    $OFF
set PROFILE_2(SHORT_JT_RAMPON)    $OFF_DELAY
set PROFILE_2(SHORT_MULTIEXECUTE) 0
set PROFILE_2(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_2(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_2(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_2(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_2(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_2(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_2(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_2(SHORT_OFF_HUE) {361 range 0 - 361}
set PROFILE_2(SHORT_OFF_LEVEL) 0.000000
set PROFILE_2(SHORT_OFF_SATURATION) 1.01
set PROFILE_2(SHORT_OFF_TIME_BASE) 7
set PROFILE_2(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_2(SHORT_OFF_TIME_MODE) 0
set PROFILE_2(SHORT_ONDELAY_MODE) 0
set PROFILE_2(SHORT_ONDELAY_TIME_BASE) 0
set PROFILE_2(SHORT_ONDELAY_TIME_FACTOR) 0
set PROFILE_2(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_2(SHORT_ON_HUE) {361 range 0 - 361}
set PROFILE_2(SHORT_ON_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_2(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_2(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_2(SHORT_ON_TIME_BASE) 7
set PROFILE_2(SHORT_ON_TIME_FACTOR) 31
set PROFILE_2(SHORT_ON_TIME_MODE) 0
set PROFILE_2(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_2(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_2(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_2(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_2(SHORT_RAMPON_TIME_BASE) 0
set PROFILE_2(SHORT_RAMPON_TIME_FACTOR) 5
set PROFILE_2(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_2(UI_DESCRIPTION) ""
set PROFILE_2(UI_HINT)  2
set PROFILE_2(UI_TEMPLATE)    $PROFILE_2(UI_DESCRIPTION)

set PROFILE_3(LONG_COND_VALUE_HI) 150
set PROFILE_3(LONG_COND_VALUE_LO) 50
set PROFILE_3(LONG_CT_OFF) 0
set PROFILE_3(LONG_CT_OFFDELAY) 0
set PROFILE_3(LONG_CT_ON) 0
set PROFILE_3(LONG_CT_ONDELAY) 0
set PROFILE_3(LONG_CT_RAMPOFF) 0
set PROFILE_3(LONG_CT_RAMPON) 0
set PROFILE_3(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_3(LONG_DIM_MAX_HUE) {360 359}
set PROFILE_3(LONG_DIM_MAX_LEVEL) {1.000 range 0.000  - 1.000}
set PROFILE_3(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_3(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_3(LONG_DIM_MIN_HUE) 0
set PROFILE_3(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_3(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_3(LONG_DIM_STEP) {0.05 range 0.00 - 1.00}
set PROFILE_3(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_3(LONG_DIM_STEP_HUE) {0 5}
set PROFILE_3(LONG_DIM_STEP_SATURATION) {0 0.05}
set PROFILE_3(LONG_JT_OFF)      $ON_DELAY
set PROFILE_3(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_3(LONG_JT_ON)       $OFF_DELAY
set PROFILE_3(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_3(LONG_JT_RAMPOFF)  $OFF
set PROFILE_3(LONG_JT_RAMPON)   $ON
set PROFILE_3(LONG_MULTIEXECUTE) 1
set PROFILE_3(LONG_OFFDELAY_BLINK) 1
set PROFILE_3(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_3(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_3(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_3(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_3(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_3(LONG_OFF_HUE) {361 range 0 - 361}
set PROFILE_3(LONG_OFF_LEVEL) 0.000000
set PROFILE_3(LONG_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_3(LONG_OFF_TIME_BASE) 7
set PROFILE_3(LONG_OFF_TIME_FACTOR) 31
set PROFILE_3(LONG_OFF_TIME_MODE) 0
set PROFILE_3(LONG_ONDELAY_MODE) 0
set PROFILE_3(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_3(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_3(LONG_ON_HUE) {361 range 0 - 361}
set PROFILE_3(LONG_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_3(LONG_ON_MIN_LEVEL) {0 0.1}
set PROFILE_3(LONG_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_3(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_3(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_3(LONG_ON_TIME_MODE) 0
set PROFILE_3(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_3(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_LAST_DIR $NOT_ACTIVE}]
set PROFILE_3(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_3(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_3(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_3(LONG_RAMP_START_STEP) 0.050000
set PROFILE_3(SHORT_COND_VALUE_HI) 150
set PROFILE_3(SHORT_COND_VALUE_LO) 50
set PROFILE_3(SHORT_CT_OFF) 0
set PROFILE_3(SHORT_CT_OFFDELAY) 0
set PROFILE_3(SHORT_CT_ON) 0
set PROFILE_3(SHORT_CT_ONDELAY) 0
set PROFILE_3(SHORT_CT_RAMPOFF) 0
set PROFILE_3(SHORT_CT_RAMPON) 0
set PROFILE_3(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_3(SHORT_DIM_MAX_HUE) {360 359}
set PROFILE_3(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_3(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_3(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_3(SHORT_DIM_MIN_HUE) {360 0}
set PROFILE_3(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_3(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_3(SHORT_DIM_STEP) 0.050000
set PROFILE_3(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_3(SHORT_DIM_STEP_HUE) {0 5}
set PROFILE_3(SHORT_DIM_STEP_SATURATION) {0 0.05}
set PROFILE_3(SHORT_JT_OFF)       $ON_DELAY
set PROFILE_3(SHORT_JT_OFFDELAY)  $RAMP_OFF
set PROFILE_3(SHORT_JT_ON)        $OFF_DELAY
set PROFILE_3(SHORT_JT_ONDELAY)   $RAMP_ON
set PROFILE_3(SHORT_JT_RAMPOFF)   $OFF
set PROFILE_3(SHORT_JT_RAMPON)    $ON
set PROFILE_3(SHORT_MULTIEXECUTE) 0
set PROFILE_3(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_3(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_3(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_3(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_3(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_3(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_3(SHORT_OFF_HUE) {361 range 0 - 361}
set PROFILE_3(SHORT_OFF_LEVEL) 0.000000
set PROFILE_3(SHORT_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_3(SHORT_OFF_TIME_BASE) 7
set PROFILE_3(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_3(SHORT_OFF_TIME_MODE) 0
set PROFILE_3(SHORT_ONDELAY_MODE) 0
set PROFILE_3(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_3(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_3(SHORT_ON_HUE) {361 range 0 - 361}
set PROFILE_3(SHORT_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_3(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_3(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_3(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_3(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_3(SHORT_ON_TIME_MODE) 0
set PROFILE_3(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_3(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_3(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_3(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_3(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_3(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_3(UI_DESCRIPTION) ""
set PROFILE_3(UI_HINT)  3
set PROFILE_3(UI_TEMPLATE)    $PROFILE_3(UI_DESCRIPTION)

set PROFILE_4(LONG_COND_VALUE_HI) 150
set PROFILE_4(LONG_COND_VALUE_LO) 50
set PROFILE_4(LONG_CT_OFF) 0
set PROFILE_4(LONG_CT_OFFDELAY) 0
set PROFILE_4(LONG_CT_ON) 0
set PROFILE_4(LONG_CT_ONDELAY) 0
set PROFILE_4(LONG_CT_RAMPOFF) 0
set PROFILE_4(LONG_CT_RAMPON) 0
set PROFILE_4(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_4(LONG_DIM_MAX_HUE) {360 range 0 - 360}
set PROFILE_4(LONG_DIM_MAX_LEVEL) {1.000 range 0.000  - 1.000}
set PROFILE_4(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_4(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_4(LONG_DIM_MIN_HUE) {0 range 0 - 360}
set PROFILE_4(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_4(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_4(LONG_DIM_STEP) 0
set PROFILE_4(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_4(LONG_DIM_STEP_HUE) {5 range 0 - 180}
set PROFILE_4(LONG_DIM_STEP_SATURATION) 0
set PROFILE_4(LONG_JT_OFF)      $ON_DELAY
set PROFILE_4(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_4(LONG_JT_ON)       $RAMP_ON
set PROFILE_4(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_4(LONG_JT_RAMPOFF)  $RAMP_ON
set PROFILE_4(LONG_JT_RAMPON)   $ON
set PROFILE_4(LONG_MULTIEXECUTE) 1
set PROFILE_4(LONG_OFFDELAY_BLINK) {1 0}
set PROFILE_4(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_4(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_4(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_4(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_4(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_4(LONG_OFF_HUE) 0
set PROFILE_4(LONG_OFF_LEVEL) 0.000000
set PROFILE_4(LONG_OFF_SATURATION) 0.000000
set PROFILE_4(LONG_OFF_TIME_BASE) 7
set PROFILE_4(LONG_OFF_TIME_FACTOR) 31
set PROFILE_4(LONG_OFF_TIME_MODE) 0
set PROFILE_4(LONG_ONDELAY_MODE) 0
set PROFILE_4(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_4(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_4(LONG_ON_HUE) {359 range 0 - 361}
set PROFILE_4(LONG_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_4(LONG_ON_MIN_LEVEL) 0.100000
set PROFILE_4(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_4(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_4(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_4(LONG_ON_TIME_MODE) 0
set PROFILE_4(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_4(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_UP $NOT_ACTIVE}]
set PROFILE_4(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_4(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_4(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_4(LONG_RAMP_START_STEP) 0.050000
set PROFILE_4(SHORT_COND_VALUE_HI) 150
set PROFILE_4(SHORT_COND_VALUE_LO) 50
set PROFILE_4(SHORT_CT_OFF) 0
set PROFILE_4(SHORT_CT_OFFDELAY) 0
set PROFILE_4(SHORT_CT_ON) 0
set PROFILE_4(SHORT_CT_ONDELAY) 0
set PROFILE_4(SHORT_CT_RAMPOFF) 0
set PROFILE_4(SHORT_CT_RAMPON) 0
set PROFILE_4(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_4(SHORT_DIM_MAX_HUE) {360 range 0 - 360}
set PROFILE_4(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_4(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_4(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_4(SHORT_DIM_MIN_HUE) {360 range 0 - 360}
set PROFILE_4(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_4(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_4(SHORT_DIM_STEP) 0
set PROFILE_4(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_4(SHORT_DIM_STEP_HUE) 5
set PROFILE_4(SHORT_DIM_STEP_SATURATION) 0
set PROFILE_4(SHORT_JT_OFF)      $ON_DELAY
set PROFILE_4(SHORT_JT_OFFDELAY) $ON
set PROFILE_4(SHORT_JT_ON)       [subst {$ON_DELAY $ON}]
set PROFILE_4(SHORT_JT_ONDELAY)  $ON_DELAY
set PROFILE_4(SHORT_JT_RAMPOFF)  $RAMP_ON
set PROFILE_4(SHORT_JT_RAMPON)   $RAMP_ON
set PROFILE_4(SHORT_MULTIEXECUTE) 0
set PROFILE_4(SHORT_OFFDELAY_BLINK) {0 1}
set PROFILE_4(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_4(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_4(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_4(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_4(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_4(SHORT_OFF_HUE) 361
set PROFILE_4(SHORT_OFF_LEVEL) 1.01
set PROFILE_4(SHORT_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_4(SHORT_OFF_TIME_BASE) 7
set PROFILE_4(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_4(SHORT_OFF_TIME_MODE) 0
set PROFILE_4(SHORT_ONDELAY_MODE) 0
set PROFILE_4(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_4(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_4(SHORT_ON_HUE) {359 range 0 - 361}
set PROFILE_4(SHORT_ON_LEVEL) {1.010 range 0.000 - 1.010}
set PROFILE_4(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_4(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_4(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_4(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_4(SHORT_ON_TIME_MODE) 0
set PROFILE_4(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_4(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_4(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_4(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_4(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_4(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_4(UI_DESCRIPTION) ""
set PROFILE_4(UI_HINT)  4
set PROFILE_4(UI_TEMPLATE)    $PROFILE_4(UI_DESCRIPTION)

set PROFILE_5(LONG_COND_VALUE_HI) 150
set PROFILE_5(LONG_COND_VALUE_LO) 50
set PROFILE_5(LONG_CT_OFF) 0
set PROFILE_5(LONG_CT_OFFDELAY) 0
set PROFILE_5(LONG_CT_ON) 0
set PROFILE_5(LONG_CT_ONDELAY) 0
set PROFILE_5(LONG_CT_RAMPOFF) 0
set PROFILE_5(LONG_CT_RAMPON) 0
set PROFILE_5(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_5(LONG_DIM_MAX_HUE) {360 range 0 - 361}
set PROFILE_5(LONG_DIM_MAX_LEVEL) {1.000 range 0.000  - 1.000}
set PROFILE_5(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_5(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_5(LONG_DIM_MIN_HUE) {0 range 0 - 361}
set PROFILE_5(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_5(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_5(LONG_DIM_STEP) 0
set PROFILE_5(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_5(LONG_DIM_STEP_HUE) {5 range 0 - 180}
set PROFILE_5(LONG_DIM_STEP_SATURATION) 0
set PROFILE_5(LONG_JT_OFF)      $OFF
set PROFILE_5(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_5(LONG_JT_ON)       $RAMP_OFF
set PROFILE_5(LONG_JT_ONDELAY)  $OFF
set PROFILE_5(LONG_JT_RAMPOFF)  $OFF
set PROFILE_5(LONG_JT_RAMPON)   $OFF_DELAY
set PROFILE_5(LONG_MULTIEXECUTE) 1
set PROFILE_5(LONG_OFFDELAY_BLINK) 1
set PROFILE_5(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_5(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_5(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_5(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_5(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_5(LONG_OFF_HUE) 0
set PROFILE_5(LONG_OFF_LEVEL) 0.000000
set PROFILE_5(LONG_OFF_SATURATION) 0.000000
set PROFILE_5(LONG_OFF_TIME_BASE) 7
set PROFILE_5(LONG_OFF_TIME_FACTOR) 31
set PROFILE_5(LONG_OFF_TIME_MODE) 0
set PROFILE_5(LONG_ONDELAY_MODE) 0
set PROFILE_5(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_5(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_5(LONG_ON_HUE) {359 range 0 - 361}
set PROFILE_5(LONG_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_5(LONG_ON_MIN_LEVEL) 0.100000
set PROFILE_5(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_5(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_5(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_5(LONG_ON_TIME_MODE) 0
set PROFILE_5(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_5(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_DOWN $NOT_ACTIVE}]
set PROFILE_5(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_5(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_5(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_5(LONG_RAMP_START_STEP) 0.050000
set PROFILE_5(SHORT_COND_VALUE_HI) 150
set PROFILE_5(SHORT_COND_VALUE_LO) 50
set PROFILE_5(SHORT_CT_OFF) 0
set PROFILE_5(SHORT_CT_OFFDELAY) 0
set PROFILE_5(SHORT_CT_ON) 0
set PROFILE_5(SHORT_CT_ONDELAY) 0
set PROFILE_5(SHORT_CT_RAMPOFF) 0
set PROFILE_5(SHORT_CT_RAMPON) 0
set PROFILE_5(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_5(SHORT_DIM_MAX_HUE) {360 range 0 - 360}
set PROFILE_5(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_5(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_5(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_5(SHORT_DIM_MIN_HUE) {360 range 0 - 360}
set PROFILE_5(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_5(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_5(SHORT_DIM_STEP) 0
set PROFILE_5(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_5(SHORT_DIM_STEP_HUE) 5
set PROFILE_5(SHORT_DIM_STEP_SATURATION) 0
set PROFILE_5(SHORT_JT_OFF)      $OFF
set PROFILE_5(SHORT_JT_OFFDELAY) $RAMP_OFF
set PROFILE_5(SHORT_JT_ON)       $OFF_DELAY
set PROFILE_5(SHORT_JT_ONDELAY)  $OFF
set PROFILE_5(SHORT_JT_RAMPOFF)  $OFF
set PROFILE_5(SHORT_JT_RAMPON)   $OFF_DELAY
set PROFILE_5(SHORT_MULTIEXECUTE) 0
set PROFILE_5(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_5(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_5(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_5(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_5(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_5(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_5(SHORT_OFF_HUE) {0 range 0 - 361}
set PROFILE_5(SHORT_OFF_LEVEL) 1.01
set PROFILE_5(SHORT_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_5(SHORT_OFF_TIME_BASE) 7
set PROFILE_5(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_5(SHORT_OFF_TIME_MODE) 0
set PROFILE_5(SHORT_ONDELAY_MODE) 0
set PROFILE_5(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_5(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_5(SHORT_ON_HUE) {359 range 0 - 361}
set PROFILE_5(SHORT_ON_LEVEL) {1.010 range 0.000 - 1.010}
set PROFILE_5(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_5(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_5(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_5(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_5(SHORT_ON_TIME_MODE) 0
set PROFILE_5(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_5(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_5(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_5(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_5(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_5(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_5(UI_DESCRIPTION) ""
set PROFILE_5(UI_HINT)  5
set PROFILE_5(UI_TEMPLATE)    $PROFILE_5(UI_DESCRIPTION)

set PROFILE_6(LONG_COND_VALUE_HI) 150
set PROFILE_6(LONG_COND_VALUE_LO) 50
set PROFILE_6(LONG_CT_OFF) 0
set PROFILE_6(LONG_CT_OFFDELAY) 0
set PROFILE_6(LONG_CT_ON) 0
set PROFILE_6(LONG_CT_ONDELAY) 0
set PROFILE_6(LONG_CT_RAMPOFF) 0
set PROFILE_6(LONG_CT_RAMPON) 0
set PROFILE_6(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_6(LONG_DIM_MAX_HUE) {360 range 0 - 361}
set PROFILE_6(LONG_DIM_MAX_LEVEL) {1.000 range 0.000  - 1.000}
set PROFILE_6(LONG_DIM_MAX_SATURATION) 1.000000
set PROFILE_6(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_6(LONG_DIM_MIN_HUE) {0 range 0 - 361}
set PROFILE_6(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_6(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_6(LONG_DIM_STEP) {0 0.05}
set PROFILE_6(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_6(LONG_DIM_STEP_HUE) {5 range 0 - 180}
set PROFILE_6(LONG_DIM_STEP_SATURATION) {0 0.05}
set PROFILE_6(LONG_JT_OFF)      $ON_DELAY
set PROFILE_6(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_6(LONG_JT_ON)       $OFF_DELAY
set PROFILE_6(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_6(LONG_JT_RAMPOFF)  $OFF
set PROFILE_6(LONG_JT_RAMPON)   $ON
set PROFILE_6(LONG_MULTIEXECUTE) 1
set PROFILE_6(LONG_OFFDELAY_BLINK) 1
set PROFILE_6(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_6(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_6(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_6(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_6(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_6(LONG_OFF_HUE) {0 361}
set PROFILE_6(LONG_OFF_LEVEL) 0.000000
set PROFILE_6(LONG_OFF_SATURATION) {0.000000 1.01}
set PROFILE_6(LONG_OFF_TIME_BASE) 7
set PROFILE_6(LONG_OFF_TIME_FACTOR) 31
set PROFILE_6(LONG_OFF_TIME_MODE) 0
set PROFILE_6(LONG_ONDELAY_MODE) 0
set PROFILE_6(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_6(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_6(LONG_ON_HUE) {359 range 0 - 361}
set PROFILE_6(LONG_ON_LEVEL) {1.000 range 0.000 - 1.000}
set PROFILE_6(LONG_ON_MIN_LEVEL) {0.0 0.1}
set PROFILE_6(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_6(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_6(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_6(LONG_ON_TIME_MODE) 0
set PROFILE_6(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_6(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_LAST_DIR $NOT_ACTIVE}]
set PROFILE_6(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_6(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_6(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_6(LONG_RAMP_START_STEP) 0.050000
set PROFILE_6(SHORT_COND_VALUE_HI) 150
set PROFILE_6(SHORT_COND_VALUE_LO) 50
set PROFILE_6(SHORT_CT_OFF) 0
set PROFILE_6(SHORT_CT_OFFDELAY) 0
set PROFILE_6(SHORT_CT_ON) 0
set PROFILE_6(SHORT_CT_ONDELAY) 0
set PROFILE_6(SHORT_CT_RAMPOFF) 0
set PROFILE_6(SHORT_CT_RAMPON) 0
set PROFILE_6(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_6(SHORT_DIM_MAX_HUE) {360 range 0 - 360}
set PROFILE_6(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_6(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_6(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_6(SHORT_DIM_MIN_HUE) {360 range 0 - 360}
set PROFILE_6(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_6(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_6(SHORT_DIM_STEP) {0 0.05}
set PROFILE_6(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_6(SHORT_DIM_STEP_HUE) 5
set PROFILE_6(SHORT_DIM_STEP_SATURATION) {0 0.05}
set PROFILE_6(SHORT_JT_OFF)      $ON_DELAY
set PROFILE_6(SHORT_JT_OFFDELAY) $RAMP_OFF
set PROFILE_6(SHORT_JT_ON)       [subst {$ON_DELAY $OFF_DELAY}]
set PROFILE_6(SHORT_JT_ONDELAY)  $RAMP_ON
set PROFILE_6(SHORT_JT_RAMPOFF)  $OFF
set PROFILE_6(SHORT_JT_RAMPON)   $ON
set PROFILE_6(SHORT_MULTIEXECUTE) 0
set PROFILE_6(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_6(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_6(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_6(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_6(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_6(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_6(SHORT_OFF_HUE) {0 range 0 - 361}
set PROFILE_6(SHORT_OFF_LEVEL) {1.01 0.0}
set PROFILE_6(SHORT_OFF_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_6(SHORT_OFF_TIME_BASE) 7
set PROFILE_6(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_6(SHORT_OFF_TIME_MODE) 0
set PROFILE_6(SHORT_ONDELAY_MODE) 0
set PROFILE_6(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_6(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_6(SHORT_ON_HUE) {359 range 0 - 361}
set PROFILE_6(SHORT_ON_LEVEL) {1.010 range 0.000 - 1.010}
set PROFILE_6(SHORT_ON_MIN_LEVEL) 0.100000
set PROFILE_6(SHORT_ON_SATURATION) {1.01 range 0.0 - 1.01}
set PROFILE_6(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_6(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_6(SHORT_ON_TIME_MODE) 0
set PROFILE_6(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_6(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_6(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_6(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_6(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_6(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_6(UI_DESCRIPTION) ""
set PROFILE_6(UI_HINT)  6
set PROFILE_6(UI_TEMPLATE)    $PROFILE_6(UI_DESCRIPTION)

set PROFILE_7(LONG_COND_VALUE_HI) 150
set PROFILE_7(LONG_COND_VALUE_LO) 50
set PROFILE_7(LONG_CT_OFF) 0
set PROFILE_7(LONG_CT_OFFDELAY) 0
set PROFILE_7(LONG_CT_ON) 0
set PROFILE_7(LONG_CT_ONDELAY) 0
set PROFILE_7(LONG_CT_RAMPOFF) 0
set PROFILE_7(LONG_CT_RAMPON) 0
set PROFILE_7(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_7(LONG_DIM_MAX_HUE) 360
set PROFILE_7(LONG_DIM_MAX_LEVEL) 1.0
set PROFILE_7(LONG_DIM_MAX_SATURATION) {1.000 range 0.000 - 1.000}
set PROFILE_7(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_7(LONG_DIM_MIN_HUE) 360
set PROFILE_7(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_7(LONG_DIM_MIN_SATURATION) 0.000000
set PROFILE_7(LONG_DIM_STEP) 0
set PROFILE_7(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_7(LONG_DIM_STEP_HUE) 0
set PROFILE_7(LONG_DIM_STEP_SATURATION) {0.100 range 0.000 - 1.000}
set PROFILE_7(LONG_JT_OFF)      $ON_DELAY
set PROFILE_7(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_7(LONG_JT_ON)       $RAMP_ON
set PROFILE_7(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_7(LONG_JT_RAMPOFF)  $RAMP_ON
set PROFILE_7(LONG_JT_RAMPON)   $ON
set PROFILE_7(LONG_MULTIEXECUTE) 1
set PROFILE_7(LONG_OFFDELAY_BLINK) {1 0}
set PROFILE_7(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_7(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_7(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_7(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_7(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_7(LONG_OFF_HUE) 0
set PROFILE_7(LONG_OFF_LEVEL) 0.000000
set PROFILE_7(LONG_OFF_SATURATION) 0.000000
set PROFILE_7(LONG_OFF_TIME_BASE) 7
set PROFILE_7(LONG_OFF_TIME_FACTOR) 31
set PROFILE_7(LONG_OFF_TIME_MODE) 0
set PROFILE_7(LONG_ONDELAY_MODE) 0
set PROFILE_7(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_7(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_7(LONG_ON_HUE) 359
set PROFILE_7(LONG_ON_LEVEL) 1.000
set PROFILE_7(LONG_ON_MIN_LEVEL) 0.100000
set PROFILE_7(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_7(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_7(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_7(LONG_ON_TIME_MODE) 0
set PROFILE_7(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_7(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_UP $NOT_ACTIVE}]
set PROFILE_7(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_7(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_7(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_7(LONG_RAMP_START_STEP) 0.050000
set PROFILE_7(SHORT_COND_VALUE_HI) 150
set PROFILE_7(SHORT_COND_VALUE_LO) 50
set PROFILE_7(SHORT_CT_OFF) 0
set PROFILE_7(SHORT_CT_OFFDELAY) 0
set PROFILE_7(SHORT_CT_ON) 0
set PROFILE_7(SHORT_CT_ONDELAY) 0
set PROFILE_7(SHORT_CT_RAMPOFF) 0
set PROFILE_7(SHORT_CT_RAMPON) 0
set PROFILE_7(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_7(SHORT_DIM_MAX_HUE) 360
set PROFILE_7(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_7(SHORT_DIM_MAX_SATURATION) {1.0 range 0.000 - 1.000}
set PROFILE_7(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_7(SHORT_DIM_MIN_HUE) 360
set PROFILE_7(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_7(SHORT_DIM_MIN_SATURATION) 0.000000
set PROFILE_7(SHORT_DIM_STEP) 0
set PROFILE_7(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_7(SHORT_DIM_STEP_HUE) 0
set PROFILE_7(SHORT_DIM_STEP_SATURATION) 0.1
set PROFILE_7(SHORT_JT_OFF)      $ON_DELAY
set PROFILE_7(SHORT_JT_OFFDELAY) $ON
set PROFILE_7(SHORT_JT_ON)       [subst {$ON_DELAY $RAMP_ON}]
set PROFILE_7(SHORT_JT_ONDELAY)  $ON_DELAY
set PROFILE_7(SHORT_JT_RAMPOFF)  $RAMP_ON
set PROFILE_7(SHORT_JT_RAMPON)   $RAMP_ON
set PROFILE_7(SHORT_MULTIEXECUTE) 0
set PROFILE_7(SHORT_OFFDELAY_BLINK) {0 1}
set PROFILE_7(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_7(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_7(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_7(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_7(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_7(SHORT_OFF_HUE) 361
set PROFILE_7(SHORT_OFF_LEVEL) 1.01
set PROFILE_7(SHORT_OFF_SATURATION) 0
set PROFILE_7(SHORT_OFF_TIME_BASE) 7
set PROFILE_7(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_7(SHORT_OFF_TIME_MODE) 0
set PROFILE_7(SHORT_ONDELAY_MODE) 0
set PROFILE_7(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_7(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_7(SHORT_ON_HUE) 361
set PROFILE_7(SHORT_ON_LEVEL) 1.01
set PROFILE_7(SHORT_ON_MIN_LEVEL) 0.10
set PROFILE_7(SHORT_ON_SATURATION) {1.000 range 0.000 - 1.000}
set PROFILE_7(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_7(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_7(SHORT_ON_TIME_MODE) 0
set PROFILE_7(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_7(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_7(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_7(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_7(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_7(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_7(UI_DESCRIPTION) ""
set PROFILE_7(UI_HINT)  7
set PROFILE_7(UI_TEMPLATE)    $PROFILE_7(UI_DESCRIPTION)

set PROFILE_8(LONG_COND_VALUE_HI) 150
set PROFILE_8(LONG_COND_VALUE_LO) 50
set PROFILE_8(LONG_CT_OFF) 0
set PROFILE_8(LONG_CT_OFFDELAY) 0
set PROFILE_8(LONG_CT_ON) 0
set PROFILE_8(LONG_CT_ONDELAY) 0
set PROFILE_8(LONG_CT_RAMPOFF) 0
set PROFILE_8(LONG_CT_RAMPON) 0
set PROFILE_8(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_8(LONG_DIM_MAX_HUE) 360
set PROFILE_8(LONG_DIM_MAX_LEVEL) 1.0
set PROFILE_8(LONG_DIM_MAX_SATURATION) {1.0 range 0.000 - 1.000}
set PROFILE_8(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_8(LONG_DIM_MIN_HUE) 360
set PROFILE_8(LONG_DIM_MIN_LEVEL) 0.000
set PROFILE_8(LONG_DIM_MIN_SATURATION) {0.0 range 0.000 - 1.000}
set PROFILE_8(LONG_DIM_STEP) 0
set PROFILE_8(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_8(LONG_DIM_STEP_HUE) 0
set PROFILE_8(LONG_DIM_STEP_SATURATION) {0.100 range 0.000 - 1.000}
set PROFILE_8(LONG_JT_OFF)      $OFF
set PROFILE_8(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_8(LONG_JT_ON)       $RAMP_OFF
set PROFILE_8(LONG_JT_ONDELAY)  $OFF
set PROFILE_8(LONG_JT_RAMPOFF)  $OFF
set PROFILE_8(LONG_JT_RAMPON)   $OFF_DELAY
set PROFILE_8(LONG_MULTIEXECUTE) 1
set PROFILE_8(LONG_OFFDELAY_BLINK) 1
set PROFILE_8(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_8(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_8(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_8(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_8(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_8(LONG_OFF_HUE) 0
set PROFILE_8(LONG_OFF_LEVEL) 0.000000
set PROFILE_8(LONG_OFF_SATURATION) 0.000000
set PROFILE_8(LONG_OFF_TIME_BASE) 7
set PROFILE_8(LONG_OFF_TIME_FACTOR) 31
set PROFILE_8(LONG_OFF_TIME_MODE) 0
set PROFILE_8(LONG_ONDELAY_MODE) 0
set PROFILE_8(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_8(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_8(LONG_ON_HUE) 359
set PROFILE_8(LONG_ON_LEVEL) 0.000
set PROFILE_8(LONG_ON_MIN_LEVEL) 0.0
set PROFILE_8(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_8(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_8(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_8(LONG_ON_TIME_MODE) 0
set PROFILE_8(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_8(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_DOWN $NOT_ACTIVE}]
set PROFILE_8(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_8(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_8(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_8(LONG_RAMP_START_STEP) 0.050000
set PROFILE_8(SHORT_COND_VALUE_HI) 150
set PROFILE_8(SHORT_COND_VALUE_LO) 50
set PROFILE_8(SHORT_CT_OFF) 0
set PROFILE_8(SHORT_CT_OFFDELAY) 0
set PROFILE_8(SHORT_CT_ON) 0
set PROFILE_8(SHORT_CT_ONDELAY) 0
set PROFILE_8(SHORT_CT_RAMPOFF) 0
set PROFILE_8(SHORT_CT_RAMPON) 0
set PROFILE_8(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_8(SHORT_DIM_MAX_HUE) 360
set PROFILE_8(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_8(SHORT_DIM_MAX_SATURATION) 1.000000
set PROFILE_8(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_8(SHORT_DIM_MIN_HUE) 360
set PROFILE_8(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_8(SHORT_DIM_MIN_SATURATION) {0.0 range 0.000 - 1.000}
set PROFILE_8(SHORT_DIM_STEP) 0
set PROFILE_8(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_8(SHORT_DIM_STEP_HUE) 0
set PROFILE_8(SHORT_DIM_STEP_SATURATION) 0.1
set PROFILE_8(SHORT_JT_OFF)      $OFF
set PROFILE_8(SHORT_JT_OFFDELAY) $RAMP_OFF
set PROFILE_8(SHORT_JT_ON)       $OFF_DELAY
set PROFILE_8(SHORT_JT_ONDELAY)  $OFF
set PROFILE_8(SHORT_JT_RAMPOFF)  $OFF
set PROFILE_8(SHORT_JT_RAMPON)   $OFF_DELAY
set PROFILE_8(SHORT_MULTIEXECUTE) 0
set PROFILE_8(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_8(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_8(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_8(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_8(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_8(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_8(SHORT_OFF_HUE) 361
set PROFILE_8(SHORT_OFF_LEVEL) 1.01
set PROFILE_8(SHORT_OFF_SATURATION) {0.000 range 0.000 - 1.000}
set PROFILE_8(SHORT_OFF_TIME_BASE) 7
set PROFILE_8(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_8(SHORT_OFF_TIME_MODE) 0
set PROFILE_8(SHORT_ONDELAY_MODE) 0
set PROFILE_8(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_8(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_8(SHORT_ON_HUE) 361
set PROFILE_8(SHORT_ON_LEVEL) 1.01
set PROFILE_8(SHORT_ON_MIN_LEVEL) 0.10
set PROFILE_8(SHORT_ON_SATURATION) {1.000 range 0.000 - 1.000}
set PROFILE_8(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_8(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_8(SHORT_ON_TIME_MODE) 0
set PROFILE_8(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_8(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_8(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_8(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_8(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_8(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_8(UI_DESCRIPTION) ""
set PROFILE_8(UI_HINT)  8
set PROFILE_8(UI_TEMPLATE)    $PROFILE_8(UI_DESCRIPTION)

set PROFILE_9(LONG_COND_VALUE_HI) 150
set PROFILE_9(LONG_COND_VALUE_LO) 50
set PROFILE_9(LONG_CT_OFF) 0
set PROFILE_9(LONG_CT_OFFDELAY) 0
set PROFILE_9(LONG_CT_ON) 0
set PROFILE_9(LONG_CT_ONDELAY) 0
set PROFILE_9(LONG_CT_RAMPOFF) 0
set PROFILE_9(LONG_CT_RAMPON) 0
set PROFILE_9(LONG_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_9(LONG_DIM_MAX_HUE) 360
set PROFILE_9(LONG_DIM_MAX_LEVEL) 1.0
set PROFILE_9(LONG_DIM_MAX_SATURATION) {1.000 range 0.000 - 1.000}
set PROFILE_9(LONG_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_9(LONG_DIM_MIN_HUE) 360
set PROFILE_9(LONG_DIM_MIN_LEVEL) {0.000 range 0.000 - 1.000}
set PROFILE_9(LONG_DIM_MIN_SATURATION) {0.000 range 0.000 - 1.000}
set PROFILE_9(LONG_DIM_STEP) 0
set PROFILE_9(LONG_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_9(LONG_DIM_STEP_HUE) 0
set PROFILE_9(LONG_DIM_STEP_SATURATION) {0.100 range 0.000 - 1.000}
set PROFILE_9(LONG_JT_OFF)      $ON_DELAY
set PROFILE_9(LONG_JT_OFFDELAY) $RAMP_OFF
set PROFILE_9(LONG_JT_ON)       $OFF_DELAY
set PROFILE_9(LONG_JT_ONDELAY)  $RAMP_ON
set PROFILE_9(LONG_JT_RAMPOFF)  $OFF
set PROFILE_9(LONG_JT_RAMPON)   $ON
set PROFILE_9(LONG_MULTIEXECUTE) 1
set PROFILE_9(LONG_OFFDELAY_BLINK) 1
set PROFILE_9(LONG_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_9(LONG_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_9(LONG_OFFDELAY_STEP) 0.050000
set PROFILE_9(LONG_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(LONG_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_9(LONG_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_9(LONG_OFF_HUE) 0
set PROFILE_9(LONG_OFF_LEVEL) 0.000000
set PROFILE_9(LONG_OFF_SATURATION) 0.000000
set PROFILE_9(LONG_OFF_TIME_BASE) 7
set PROFILE_9(LONG_OFF_TIME_FACTOR) 31
set PROFILE_9(LONG_OFF_TIME_MODE) 0
set PROFILE_9(LONG_ONDELAY_MODE) 0
set PROFILE_9(LONG_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(LONG_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_9(LONG_ON_COLOR_TEMPERATURE) 10100
set PROFILE_9(LONG_ON_HUE) 359
set PROFILE_9(LONG_ON_LEVEL) 1.000
set PROFILE_9(LONG_ON_MIN_LEVEL) 0.0
set PROFILE_9(LONG_ON_SATURATION) {1.000 range 0.000 - 1.010}
set PROFILE_9(LONG_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_9(LONG_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_9(LONG_ON_TIME_MODE) 0
set PROFILE_9(LONG_OUTPUT_BEHAVIOUR) 0
set PROFILE_9(LONG_PROFILE_ACTION_TYPE) [subst {$DRIVE_LAST_DIR $NOT_ACTIVE}]
set PROFILE_9(LONG_RAMPOFF_TIME_BASE) 0
set PROFILE_9(LONG_RAMPOFF_TIME_FACTOR) 5
set PROFILE_9(LONG_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(LONG_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_9(LONG_RAMP_START_STEP) 0.050000
set PROFILE_9(SHORT_COND_VALUE_HI) 150
set PROFILE_9(SHORT_COND_VALUE_LO) 50
set PROFILE_9(SHORT_CT_OFF) 0
set PROFILE_9(SHORT_CT_OFFDELAY) 0
set PROFILE_9(SHORT_CT_ON) 0
set PROFILE_9(SHORT_CT_ONDELAY) 0
set PROFILE_9(SHORT_CT_RAMPOFF) 0
set PROFILE_9(SHORT_CT_RAMPON) 0
set PROFILE_9(SHORT_DIM_MAX_COLOR_TEMPERATURE) 10000
set PROFILE_9(SHORT_DIM_MAX_HUE) 360
set PROFILE_9(SHORT_DIM_MAX_LEVEL) 1.000000
set PROFILE_9(SHORT_DIM_MAX_SATURATION) {1.0 range 0.000 - 1.000}
set PROFILE_9(SHORT_DIM_MIN_COLOR_TEMPERATURE) 1000
set PROFILE_9(SHORT_DIM_MIN_HUE) 360
set PROFILE_9(SHORT_DIM_MIN_LEVEL) 0.000000
set PROFILE_9(SHORT_DIM_MIN_SATURATION) {0.0 range 0.000 - 1.000}
set PROFILE_9(SHORT_DIM_STEP) 0
set PROFILE_9(SHORT_DIM_STEP_COLOR_TEMPERATURE) 0
set PROFILE_9(SHORT_DIM_STEP_HUE) 0
set PROFILE_9(SHORT_DIM_STEP_SATURATION) 0.1
set PROFILE_9(SHORT_JT_OFF)      $ON_DELAY
set PROFILE_9(SHORT_JT_OFFDELAY) $RAMP_OFF
set PROFILE_9(SHORT_JT_ON)       $OFF_DELAY
set PROFILE_9(SHORT_JT_ONDELAY)  $RAMP_ON
set PROFILE_9(SHORT_JT_RAMPOFF)  $OFF
set PROFILE_9(SHORT_JT_RAMPON)   $ON
set PROFILE_9(SHORT_MULTIEXECUTE) 0
set PROFILE_9(SHORT_OFFDELAY_BLINK) {1 0}
set PROFILE_9(SHORT_OFFDELAY_BLINK_PERIOD_OFFDELAYLEVEL) 4
set PROFILE_9(SHORT_OFFDELAY_BLINK_PERIOD_OLDLEVEL) 4
set PROFILE_9(SHORT_OFFDELAY_STEP) 0.050000
set PROFILE_9(SHORT_OFFDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(SHORT_OFFDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_9(SHORT_OFF_COLOR_TEMPERATURE) 10100
set PROFILE_9(SHORT_OFF_HUE) 361
set PROFILE_9(SHORT_OFF_LEVEL) 1.01
set PROFILE_9(SHORT_OFF_SATURATION) {0.000 range 0.000 - 1.000}
set PROFILE_9(SHORT_OFF_TIME_BASE) 7
set PROFILE_9(SHORT_OFF_TIME_FACTOR) 31
set PROFILE_9(SHORT_OFF_TIME_MODE) 0
set PROFILE_9(SHORT_ONDELAY_MODE) 0
set PROFILE_9(SHORT_ONDELAY_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(SHORT_ONDELAY_TIME_FACTOR) {0 range 0 - 31}
set PROFILE_9(SHORT_ON_COLOR_TEMPERATURE) 10100
set PROFILE_9(SHORT_ON_HUE) 361
set PROFILE_9(SHORT_ON_LEVEL) 1.01
set PROFILE_9(SHORT_ON_MIN_LEVEL) 0.10
set PROFILE_9(SHORT_ON_SATURATION) {1.000 range 0.000 - 1.000}
set PROFILE_9(SHORT_ON_TIME_BASE) {7 range 0 - 7}
set PROFILE_9(SHORT_ON_TIME_FACTOR) {31 range 0 - 31}
set PROFILE_9(SHORT_ON_TIME_MODE) 0
set PROFILE_9(SHORT_OUTPUT_BEHAVIOUR) 0
set PROFILE_9(SHORT_PROFILE_ACTION_TYPE) 1
set PROFILE_9(SHORT_RAMPOFF_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(SHORT_RAMPOFF_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_9(SHORT_RAMPON_TIME_BASE) {0 range 0 - 7}
set PROFILE_9(SHORT_RAMPON_TIME_FACTOR) {5 range 0 - 31}
set PROFILE_9(SHORT_RAMP_START_STEP) 0.050000
set PROFILE_9(UI_DESCRIPTION) ""
set PROFILE_9(UI_HINT)  9
set PROFILE_9(UI_TEMPLATE)    $PROFILE_9(UI_DESCRIPTION)

set PROFILE_10(SHORT_PROFILE_ACTION_TYPE) 0
set PROFILE_10(LONG_PROFILE_ACTION_TYPE)  0
set PROFILE_10(UI_DESCRIPTION)  "Die Taste ist nicht aktiv."
set PROFILE_10(UI_TEMPLATE)   $PROFILE_8(UI_DESCRIPTION)
set PROFILE_10(UI_HINT) 10