#!/bin/sh

set help_txt "<hr>"
append help_txt "<font size='3'><span style=\"text-decoration:underline; font-weight:bold\">Der Ausgangspegel wird durch eine Verkn&uuml;pfung der 3 Kan&auml;le nach folgender Regel bestimmt:</span><br><br></font>"
append help_txt "Ausgangspegel = (((0 o A) o B) o C)<br/><br/>"
append help_txt "Es gilt dabei folgende Definition:<br/><br/>"
append help_txt "&nbsp;A = Pegel von Ch:1<br/>"
append help_txt "&nbsp;B = Pegel von Ch:2<br/>"
append help_txt "&nbsp;C = Pegel von Ch:3<br/>"
append help_txt "&nbsp;o = Verkn&uuml;pfungsregel des dazugeh&ouml;rigen Kanals<br/>"
append help_txt "&nbsp;Klammern werden von innen nach aussen abgearbeitet<br/><br/>"

append help_txt "Bedeutung der einzelnen Verkn&uuml;pfungsregeln:<br/>"
append help_txt "<ul>"
append help_txt "<li>Kanal inaktiv: Der Kanal wird bei der Verkn&uuml;pfung ignoriert.</li>"
append help_txt "<li>OR: Das Verkn&uuml;pfungsergebnis ist der h&ouml;here Pegel der verkn&uuml;pften Kan&auml;le.</li>"
append help_txt "<li>AND: Das Verkn&uuml;pfungsergebnis ist der niedrigere Pegel der verkn&uuml;pften Kan&auml;le.</li>"
append help_txt "<li>XOR: Das Verkn&uuml;pfungsergebnis ist 0%, wenn beide Kan&auml;le AN oder AUS sind. Ist nur ein Kanal AN, ist das Ergebnis der Pegel dieses Kanals.</li>"
append help_txt "<li>NOR: Es wird die Verkn&uuml;pfung OR ausgef&uuml;hrt und das Ergebniss anschlie&szlig;end invertiert (100% - Pegel).</li>"
append help_txt "<li>NAND: Es wird die Verkn&uuml;pfung AND ausgef&uuml;hrt und das Ergebniss anschlie&szlig;end invertiert (100% - Pegel).</li>"
append help_txt "<li>OR_INVERS: Der zu verkn&uuml;pfende Kanal (rechts vom 'o') wird zuerst invertiert (100% - Pegel) und anschlie&szlig;end die Verkn&uuml;pfung OR ausgef&uuml;hrt.</li>"
append help_txt "<li>AND_INVERS: Der zu verkn&uuml;pfende Kanal (rechts vom 'o') wird zuerst invertiert (100% - Pegel) und anschlie&szlig;end die Verkn&uuml;pfung AND ausgef&uuml;hrt.</li>"
append help_txt "<li>PLUS: Die beiden Pegel werden addiert (max. 100%).</li>"
append help_txt "<li>MINUS: Die beiden Pegel werden subtrahiert (min. 0%).</li>"
append help_txt "<li>MULTI: Die beiden Pegel werden multipliziert.</li>"
append help_txt "<li>PLUS_INVERS: Der zu verkn&uuml;pfende Kanal (rechts vom 'o') wird zuerst invertiert (100% - Pegel) und anschlie&szlig;end die Verkn&uuml;pfung PLUS ausgef&uuml;hrt. </li>"
append help_txt "<li>MINUS_INVERS: Der zu verkn&uuml;pfende Kanal (rechts vom 'o') wird zuerst invertiert (100% - Pegel) und anschlie&szlig;end die Verkn&uuml;pfung MINUS ausgef&uuml;hrt. </li>"
append help_txt "<li>MULTI_INVERS: Der zu verkn&uuml;pfende Kanal (rechts vom 'o') wird zuerst invertiert (100% - Pegel) und anschlie&szlig;end die Verkn&uuml;pfung MULTI ausgef&uuml;hrt. </li>"
append help_txt "<li>INVERS_PLUS: Die beiden Pegel werden addiert (max. 100%) und das Ergebnis anschlie&szlig;end invertiert (100% - Pegel)</li>"
append help_txt "<li>INVERS_MINUS: Die beiden Pegel werden subtrahiert (max. 100%) und das Ergebnis anschlie&szlig;end invertiert (100% - Pegel)</li>"
append help_txt "<li>INVERS_MULTI: Die beiden Pegel werden multipliziert und das Ergebnis anschlie&szlig;end invertiert (100% - Pegel)</li>"

append help_txt "</ul>"
append help_txt "Beispiel:<br/>"
append help_txt "<blockquote>"
append help_txt "A = 70%, B = 25%, C = 80%<br/><br/>"
append help_txt "Verkn&uuml;pfung: (((0% OR A) NOR B) AND_INVERS C)<br/><br/>"
append help_txt "0% OR A = 70%<br/>"
append help_txt "70% NOR B = 30%<br/>"
append help_txt "30% AND_INVERS C = 20%<br/><br/>"
append help_txt "Der Ausgangspegel ergibt hier 20%" 
append help_txt "</blockquote>"
